"""Typed event dataclasses for the openHarness stream.

Mirror the NDJSON shapes emitted by `oh run --output-format stream-json`
(``src/main.tsx`` stream-json branch). Keeping these in lockstep with the
CLI's output is essential — any divergence breaks streaming.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

__all__ = [
    "CostUpdate",
    "ErrorEvent",
    "Event",
    "TextDelta",
    "ToolEnd",
    "ToolStart",
    "TurnComplete",
    "UnknownEvent",
    "parse_event",
]


@dataclass(frozen=True)
class Event:
    """Base class for all streamed events. Do not instantiate directly."""


@dataclass(frozen=True)
class TextDelta(Event):
    """A chunk of text generated by the assistant."""

    content: str


@dataclass(frozen=True)
class ToolStart(Event):
    """The assistant has begun invoking a tool."""

    tool: str


@dataclass(frozen=True)
class ToolEnd(Event):
    """A tool invocation has completed."""

    tool: str
    output: str
    error: bool


@dataclass(frozen=True)
class ErrorEvent(Event):
    """A recoverable error occurred during the turn."""

    message: str


@dataclass(frozen=True)
class CostUpdate(Event):
    """Cost and token counts updated after a completed request."""

    input_tokens: int
    output_tokens: int
    cost: float
    model: str


@dataclass(frozen=True)
class TurnComplete(Event):
    """A turn has ended. ``reason`` is ``"completed"`` for normal end,
    ``"max_turns"`` when the turn cap was hit, ``"error"`` on failure, etc."""

    reason: str


@dataclass(frozen=True)
class UnknownEvent(Event):
    """Fallback for event types the SDK doesn't recognize yet.

    Kept so forward-compatible CLI versions that emit new event types
    don't break existing Python clients — they just observe an
    ``UnknownEvent`` with the raw payload.
    """

    raw: dict[str, Any]


def parse_event(obj: dict[str, Any]) -> Event:
    """Parse one NDJSON object into a typed :class:`Event`.

    Unknown ``type`` values become :class:`UnknownEvent` so forward-compatible
    CLI versions can add new event types without breaking existing clients.

    :param obj: Decoded JSON object (already run through ``json.loads``).
    :returns: A typed Event subclass.
    :raises TypeError: if ``obj`` is not a dict.
    """
    if not isinstance(obj, dict):
        raise TypeError(f"Event payload must be a dict, got {type(obj).__name__}")
    kind = obj.get("type")
    if kind == "text":
        return TextDelta(content=str(obj.get("content", "")))
    if kind == "tool_start":
        return ToolStart(tool=str(obj.get("tool", "")))
    if kind == "tool_end":
        return ToolEnd(
            tool=str(obj.get("tool", "")),
            output=str(obj.get("output", "")),
            error=bool(obj.get("error", False)),
        )
    if kind == "error":
        return ErrorEvent(message=str(obj.get("message", "")))
    if kind == "cost_update":
        return CostUpdate(
            input_tokens=int(obj.get("inputTokens", 0)),
            output_tokens=int(obj.get("outputTokens", 0)),
            cost=float(obj.get("cost", 0.0)),
            model=str(obj.get("model", "")),
        )
    if kind == "turn_complete":
        return TurnComplete(reason=str(obj.get("reason", "completed")))
    return UnknownEvent(raw=dict(obj))
